export const onboardingData = [
  {
    id: '1',
    step: 1,
    stepText: '1 of 3',
    headerTitle: 'Start Your Daily Pledge',
    title: "Tap the big green 'PLEDGE TODAY' button",
    subtitle: 'Start Your Daily Pledge',
    image: require('../assets/images/OnboardingImage/1.png'),
  },
  {
    id: '2',
    step: 1,
    stepText: '1 of 3',
    headerTitle: 'Start Your Daily Pledge',
    title: 'Choose your daily sustainability action',
    subtitle: 'Start Your Daily Pledge',
    image: require('../assets/images/OnboardingImage/2.png'),
  },
  {
    id: '3',
    step: 1,
    stepText: '1 of 3',
    headerTitle: 'Start Your Daily Pledge',
    title: 'Complete and confirm your action',
    subtitle: 'Start Your Daily Pledge',
    image: require('../assets/images/OnboardingImage/3.png'),
  },
  {
    id: '4',
    step: 1,
    stepText: '1 of 3',
    headerTitle: 'Start Your Daily Pledge',
    title: 'Earn OaVana tokens instantly!',
    subtitle: 'Start Your Daily Pledge',
    image: require('../assets/images/OnboardingImage/4.png'),
  },

  {
    id: '5',
    step: 2,
    stepText: '2 of 3',
    headerTitle: 'Get Your Personal Referral Link',
    title: 'Go to Invite → Create your unique referral code',
    subtitle: 'Get Your Personal Referral Link',
    image: require('../assets/images/OnboardingImage/5.png'),
  },
  {
    id: '6',
    step: 2,
    stepText: '2 of 3',
    headerTitle: 'Get Your Personal Referral Link',
    title: 'Copy your unique referral code',
    subtitle: 'Get Your Personal Referral Link',
    image: require('../assets/images/OnboardingImage/6.png'),
  },
  {
    id: '7',
    step: 2,
    stepText: '2 of 3',
    headerTitle: 'Get Your Personal Referral Link',
    title: 'Mine OaVana tokens at a higher rate for every friend who joins',
    subtitle: 'Get Your Personal Referral Link',
    image: require('../assets/images/OnboardingImage/7.png'),
  },
  {
    id: '8',
    step: 2,
    stepText: '2 of 3',
    headerTitle: 'Get Your Personal Referral Link',
    title: 'Build your climate action community',
    subtitle: 'Get Your Personal Referral Link',
    image: require('../assets/images/OnboardingImage/8.png'),
  },

  {
    id: '9',
    step: 3,
    stepText: '3 of 3',
    headerTitle: 'Create Your Profile',
    title: 'Sign up',
    subtitle: 'Create Your Profile',
    image: require('../assets/images/OnboardingImage/9.png'),
  },
  {
    id: '10',
    step: 3,
    stepText: '3 of 3',
    headerTitle: 'Create Your Profile',
    title: 'Set up your profile with photo & goals',
    subtitle: 'Create Your Profile',
    image: require('../assets/images/OnboardingImage/10.png'),
  },
  {
    id: '11',
    step: 3,
    stepText: '3 of 3',
    headerTitle: 'Create Your Profile',
    title: 'Tell us your location for local impact tracking',
    subtitle: 'Create Your Profile',
    image: require('../assets/images/OnboardingImage/11.png'),
  },
  {
    id: '12',
    step: 3,
    stepText: '3 of 3',
    headerTitle: 'Create Your Profile',
    title: 'Set your carbon reduction goals',
    subtitle: 'Create Your Profile',
    image: require('../assets/images/OnboardingImage/12.png'),
    isLast: true,
  },
];
